//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class EpicAuditLog
    {
        public long Id { get; set; }
        public long EpicId { get; set; }
        public string Action { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<long> CreatedBy { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Epic Epic { get; set; }
    }
}
