//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectDocument
    {
        public long Id { get; set; }
        public long ProjectId { get; set; }
        public byte[] Data { get; set; }
        public string Note { get; set; }
        public string FileXtention { get; set; }
        public string FileName { get; set; }
        public bool Rejected { get; set; }
        public long OwnerEmpID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> TaskId { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Employee Employee2 { get; set; }
        public virtual Project Project { get; set; }
        public virtual Task Task { get; set; }
    }
}
