//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public long Id { get; set; }
        public string AuthToken { get; set; }
        public long EmpId { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Expiry { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
