//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WORKAHOLICdbEntities : DbContext
    {
        public WORKAHOLICdbEntities()
            : base("name=WORKAHOLICdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommunicationType> CommunicationTypes { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmployeeRole> EmployeeRoles { get; set; }
        public virtual DbSet<Entity> Entities { get; set; }
        public virtual DbSet<Epic> Epics { get; set; }
        public virtual DbSet<EpicAuditLog> EpicAuditLogs { get; set; }
        public virtual DbSet<Feature> Features { get; set; }
        public virtual DbSet<FeatureAuditLog> FeatureAuditLogs { get; set; }
        public virtual DbSet<Lead> Leads { get; set; }
        public virtual DbSet<LeadCommunication> LeadCommunications { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Project> Projects { get; set; }
        public virtual DbSet<ProjectDocument> ProjectDocuments { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<TaskAuditLog> TaskAuditLogs { get; set; }
        public virtual DbSet<TaskProgress> TaskProgresses { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TeamMember> TeamMembers { get; set; }
        public virtual DbSet<TeamProject> TeamProjects { get; set; }
        public virtual DbSet<Token> Tokens { get; set; }
    

    }
}
